#! /usr/bin/env bash

OPENJDK=/Users/fliu/Downloads/openjdk1.8.0_222-jvmci-19.2-b02
MIX=/Users/fliu/Documents/mx

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

LIB=$DIR/dotty/lib
LIBS=$LIB/scala-library-2.12.8.jar:$LIB/dotty-library_0.17-0.17.0-RC1.jar 

export PATH=$MIX:$PATH
export JAVA_HOME=$OPENJDK/Contents/Home

$DIR/dotty/bin/dotc $DIR/lazy.scala

mx -v vm -XX:+UseJVMCICompiler -Dgraal.MethodFilter=lazyVal.*.* -Dgraal.Dump=  -cp $DIR:$LIBS lazyVal.Test
